name: disaster_response
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
- nltk=3.2.5
- pandas=0.25.1
- python=3.7*
- scikit-learn=0.24.1
- numpy=1.19.2
- spacy=2.3.5
- spacy-model-en_core_web_lg
- pip
- pip:
  - plotly==4.14.3
  - flask==1.1.2
  - sqlalchemy==1.4.7
